### ISSUE TITLE
Help : Memtable

### ISSUE THREAD

**Issue by devsohi** [danchia/ddb#1]
@danchia  I went through code for memtable . Just have few doubts 

1. is memtable lock free skiplist ?
2. does memtable only support insert operation ?

**Comment by danchia** [comment]
The memtable is indeed a lock free skiplist, and it only supports inserts.
Updates and deletes are achieved by inserting a new entry with the same key, but a fresher timestamp.

**Comment by devsohi** [comment]
@danchia Thanks for quick response . Just beginners doubt . (sorry for more questions)

1. If memtable is lock free, then what is use mu.Lock as first statement in  Insert function. 
[Here](https://github.com/danchia/ddb/blob/master/memtable/memtable.go#L76) 
 Would not this lock entire method and insertion will become sequential for that memtable ?

**Comment by danchia** [comment]
Good questions - it's actually only lock-free on reading, not insertion.
For very write-heavy workloads this may pose a problem, but I'm waiting for that to happen before worrying :)

**Comment by devsohi** [comment]
Cool. Looking forward to lock free implementation for write heavy workloads .  (also more tutorials on ddb :-) )
